Refactor/clean up correlations
genenetwork/genenetwork3 pull request #4
Opened 2021-03-14 02:47 UTC by Alexanderlacuna

Refactor code for correlation api

2021-03-15 12:00 UTC, BonfaceKilz requested changes
Also in this PR, if you deem it feasible, get rid of all of that gn2 correlations stuff that's hard to lint

2021-03-15 12:00 UTC, BonfaceKilz commented on gn3/api/correlation.py
> +    target_datasets = correlation_input.get("target_dataset")
You could get rid of some of these and make this params(since I see they are required)

/sample_r/method/:method/

2021-03-15 12:00 UTC, BonfaceKilz commented on gn3/api/correlation.py
> +    correlation_input = request.json
Should be:
```suggestion
    correlation_input = request.json()
```

2021-03-15 12:09 UTC, BonfaceKilz commented
Also @Alexanderlacuna please ensure you lint your files when before you commit!

2021-03-15 14:16 UTC, Alexanderlacuna commented
@BonfaceKilz  Thanks for the review currently everything in this branch is green. The code for the actual correlation computations isn't that much maybe if possible we could revert the previous PR and leave that to gene network 2 .

2021-03-15 16:27 UTC, BonfaceKilz commented
Alexander Kabui ***@***.***> writes:

> @BonfaceKilz Thanks for the review currently
> everything in this branch is green. The code for
> the actual correlation computations isn't that
> much maybe if possible we could revert the
> previous PR and leave that to gene network 2 .

In that case, how about you remove those files in
this branch?

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

2021-03-16 07:36 UTC, merged

2021-03-16 07:37 UTC, BonfaceKilz commented
@Alexanderlacuna I've resolved the Merge Conflicts. You could now delete all the old gn2 stuff in a different branch...